services:
  db:
    image: postgis/postgis:15-3.3
    container_name: rgwcma-gis-db
    environment:
      - POSTGRES_DB=${DB_NAME:-rgwcma_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rgw-network
    restart: always

  rgw-server:
    build:
      context: ./BACK_END/rgwcma_gis_server
    image: shubhamdata690/rgwcma-gis-server:${RGW_VERSION}
    container_name: rgwcma-gis-server
    ports:
      - "8030:8000"
    env_file:
      - ./BACK_END/rgwcma_gis_server/.env
    volumes:
      - ./BACK_END/rgwcma_gis_server/media:/app/media
      - ./BACK_END/rgwcma_gis_server/data:/app/data
    depends_on:
      - db
    restart: always
    networks:
      - rgw-network

  rgw-client:
    build:
      context: ./FRONT_END
    image: shubhamdata690/rgwcma-gis-client:${RGW_VERSION}
    container_name: rgwcma-gis-client
    ports:
      - "8031:80"
    depends_on:
      - rgw-server
    restart: always
    networks:
      - rgw-network

networks:
  rgw-network:
    driver: bridge

volumes:
  postgres_data:
