"""
Django settings for rgwcma_gis_server project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""





import os
import glob
from pathlib import Path

# ==============================================================================
# SPATIAL LIBRARIES CONFIGURATION (WINDOWS)
# ==============================================================================
if os.name == 'nt':
    # 1. Broad Detection of GIS Environments
    possible_gis_paths = [
        r"C:\OSGeo4W",
        r"C:\Program Files\QGIS 3.40.14",
    ]
    
    found_bin = None
    found_proj = None
    
    for p in possible_gis_paths:
        bin_dir = os.path.join(p, "bin")
        proj_dir = os.path.join(p, "share", "proj")
        if os.path.exists(bin_dir) and os.path.exists(os.path.join(proj_dir, "proj.db")):
            found_bin = bin_dir
            found_proj = proj_dir
            break

    if found_bin:
        # Add to DLL search path (Python 3.8+)
        if hasattr(os, 'add_dll_directory'):
            os.add_dll_directory(found_bin)
        
        # Add to PATH for older lookup mechanisms and subprocesses
        if found_bin not in os.environ['PATH']:
            os.environ['PATH'] = found_bin + os.pathsep + os.environ['PATH']
        
        import ctypes
        # 3. Set Explicit Library Paths for Django
        # Preference: gdal310 (highly compatible), then others
        gdal_libs = sorted(glob.glob(os.path.join(found_bin, "gdal*.dll")), reverse=True)
        if gdal_libs:
            # Try to find exactly gdal310.dll
            gdal310 = [lib for lib in gdal_libs if '310' in lib]
            GDAL_LIBRARY_PATH = gdal310[0] if gdal310 else gdal_libs[0]
            try:
                ctypes.CDLL(GDAL_LIBRARY_PATH)
            except Exception:
                pass
        
        geos_libs = sorted(glob.glob(os.path.join(found_bin, "geos*.dll")), reverse=True)
        if geos_libs:
            geos_c_libs = [lib for lib in geos_libs if 'geos_c' in lib]
            GEOS_LIBRARY_PATH = sorted(geos_c_libs or geos_libs, reverse=True)[0]

        # 4. Handle PROJ_LIB Consistency
        # The QGIS/OSGeo4W GDAL DLL might expect a newer proj.db layout (>= 4) 
        # but ships with an old proj.db (layout 1/2), causing GDAL_ERROR 1.
        # pyproj always ships with a valid modern proj.db, use it if possible.
        try:
            import pyproj
            os.environ["PROJ_LIB"] = pyproj.datadir.get_data_dir()
        except (ImportError, AttributeError):
            if found_proj:
                os.environ["PROJ_LIB"] = found_proj

from datetime import timedelta
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

# Load environment variables
load_dotenv()

# ==============================================================================
# PATH CONFIGURATION
# ==============================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# SECURITY SETTINGS
# ==============================================================================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$^kdt&z_65hhm&pkj-ko9m(jgxj52e6s3nu-pikq#09o9l+$e&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '127.0.0.1', 'localhost']


# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [
    # Django Core Apps
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django_extensions',
    
    # Third-Party Apps
    'rest_framework',
    'django_filters',
    
    # Local Apps
    'locationApi',
    'account_app',
    'rainfallApi',
    'raingaugeApi',
    'water_qualityApi',
    'aquiferApi',
    'rechargeStructureApi',
    'exportApi',
    'layersApi',
    'pizometerApi',
    'core',
    'waterquality_availabilityApi',
]

MIDDLEWARE = [
    "core.middleware.BrokenPipeMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]



ROOT_URLCONF = 'rgwcma_gis_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rgwcma_gis_server.wsgi.application'


# ==============================================================================
# DATABASE CONFIGURATION
# ==============================================================================
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database Selection Logic
USE_POSTGRES = os.getenv('USE_POSTGRES', 'False').lower() == 'true'

if USE_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': os.getenv('DB_NAME', 'rgwcma_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
            'HOST': os.getenv('DB_HOST', 'db'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 20,
            }
        }
    }


# ==============================================================================
# CACHING CONFIGURATION
# ==============================================================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


# ==============================================================================
# PASSWORD VALIDATION
# ==============================================================================
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ==============================================================================
# STATIC FILES
# ==============================================================================
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# CORS CONFIGURATION
# ==============================================================================

from corsheaders.defaults import default_headers

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Explicitly use standard headers for better compatibility
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-auth-key",
    "authorization",
]

CORS_ALLOWED_ORIGINS = [
    "https://rgwcma-mis.geoplanetsolution.com",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_EXPOSE_HEADERS = [
    "x-auth-key",
    "authorization",
]


# ==============================================================================
# REST FRAMEWORK CONFIGURATION
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'locationApi.authentication.ApiKeyAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}


# ==============================================================================
# JWT AUTHENTICATION CONFIGURATION
# ==============================================================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

import rgwcma_gis_server.db_wal
