services:
  web:
    build: .
    ports:
      - "8030:8030"
    volumes:
      - ./media:/app/media
      - ./data:/app/data
    env_file:
      - .env
    command: gunicorn rgwcma_gis_server.wsgi:application -w 2 -b 0.0.0.0:8030 --timeout 300
