import React, { useState, useEffect, useRef } from 'react';
import { ImageOverlay, useMap } from 'react-leaflet';
import api from '../../../api';

/**
 * Water Quality Contour Layer (Backend-Generated Image)
 * Fetches and renders a heat-map image generated by the backend.
 */
const WaterQualityContourLayer = ({
    isActive,
    parameter, // 'ec', 'nitrate', 'fluoride', 'tds'
    filters,    // To get selected GP/Block/District
    label,
    onLoading
}) => {
    const [contourImage, setContourImage] = useState(null);
    const [bounds, setBounds] = useState(null);
    const [loading, setLoading] = useState(false);
    const [opacity, setOpacity] = useState(0); // Hide until fully loaded
    const loadingRef = useRef(false);
    const map = useMap();

    // Auto-zoom when bounds are set
    useEffect(() => {
        if (isActive && bounds && map) {
            map.fitBounds(bounds, { padding: [20, 20], duration: 1.5 });
        }
    }, [bounds, isActive, map]);

    useEffect(() => {
        if (!isActive || !parameter || !filters?.district) {
            setContourImage(null);
            setBounds(null);
            setLoading(false);
            if (loadingRef.current) {
                loadingRef.current = false;
                if (onLoading) onLoading(false);
            }
            return;
        }

        const fetchContour = async () => {
            setContourImage(null);
            setBounds(null);
            setOpacity(0);
            setLoading(true);
            loadingRef.current = true;
            if (onLoading) onLoading(true);
            const gpId = filters.gp_id;
            const blockId = filters.block_id;
            const distId = filters.district_id;


            try {
                if (!gpId && !blockId && !distId) {
                    console.warn(`⚠️ ContourLayer (${parameter}): No location ID found in filters`);
                    setLoading(false);
                    if (loadingRef.current) {
                        loadingRef.current = false;
                        if (onLoading) onLoading(false);
                    }
                    return;
                }

                const response = await api.waterQuality.getContourMap({
                    gp_id: gpId,
                    block_id: blockId,
                    district_id: distId,
                    parameter: parameter
                });


                if (response && response.heatmap_url && response.bbox) {
                    const [minX, minY, maxX, maxY] = response.bbox;
                    const newBounds = [[minY, minX], [maxY, maxX]];


                    setContourImage(response.heatmap_url);
                    setBounds(newBounds);
                } else {
                    console.warn(`⚠️ ContourLayer (${parameter}): Response missing heatmap_url or bbox`, response);
                    setLoading(false);
                    if (loadingRef.current) {
                        loadingRef.current = false;
                        if (onLoading) onLoading(false);
                    }
                }
            } catch (error) {
                console.error(`❌ ContourLayer (${parameter}): Error fetching backend contour:`, error);
                setContourImage(null);
                setBounds(null);
                setLoading(false);
                if (loadingRef.current) {
                    loadingRef.current = false;
                    if (onLoading) onLoading(false);
                }
            }
        };

        fetchContour();
    }, [isActive, parameter, filters?.district, filters?.block, filters?.gramPanchayat, filters?.district_id, filters?.block_id, filters?.gp_id]);

    if (!isActive || !contourImage || !bounds) {
        return null;
    }

    return (
        <ImageOverlay
            key={`${parameter}-${bounds.toString()}`}
            url={contourImage}
            bounds={bounds}
            opacity={opacity}
            zIndex={1000}
            interactive={false}
            eventHandlers={{
                load: () => {
                    setOpacity(0.8);
                    setLoading(false);
                    if (loadingRef.current) {
                        loadingRef.current = false;
                        if (onLoading) onLoading(false);
                    }
                },
                error: () => {
                    setLoading(false);
                    if (loadingRef.current) {
                        loadingRef.current = false;
                        if (onLoading) onLoading(false);
                    }
                }
            }}
        />
    );
};

export default WaterQualityContourLayer;
