# Generated by Django 5.2.9 on 2026-02-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationApi', '0010_block_geometry_district_geometry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the well', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the well', null=True)),
                ('well_id', models.CharField(help_text='Unique identifier for the well', max_length=100, unique=True)),
                ('type_of_well', models.CharField(choices=[('bore_well', 'Bore Well'), ('dug_well', 'Dug Well'), ('hand_pump', 'Hand Pump'), ('tube_well', 'Tube Well'), ('open_well', 'Open Well'), ('other', 'Other')], default='bore_well', max_length=50)),
                ('well_depth', models.FloatField(blank=True, help_text='Depth of well in meters', null=True)),
                ('pre_ph', models.FloatField(blank=True, help_text='pH level (Pre Monsson)', null=True)),
                ('post_ph', models.FloatField(blank=True, help_text='pH level (Post Monsson)', null=True)),
                ('pre_hardness', models.FloatField(blank=True, help_text='Hardness in mg/L (Pre Monsson)', null=True)),
                ('post_hardness', models.FloatField(blank=True, help_text='Hardness in mg/L (Post Monsson)', null=True)),
                ('pre_alkalinity', models.FloatField(blank=True, help_text='Alkalinity in mg/L (Pre Monsson)', null=True)),
                ('post_alkalinity', models.FloatField(blank=True, help_text='Alkalinity in mg/L (Post Monsson)', null=True)),
                ('pre_fluoride', models.FloatField(blank=True, help_text='Fluoride in mg/L (Pre Monsson)', null=True)),
                ('post_fluoride', models.FloatField(blank=True, help_text='Fluoride in mg/L (Post Monsson)', null=True)),
                ('pre_nitrate', models.FloatField(blank=True, help_text='Nitrate in mg/L (Pre Monsson)', null=True)),
                ('post_nitrate', models.FloatField(blank=True, help_text='Nitrate in mg/L (Post Monsson)', null=True)),
                ('pre_ec', models.FloatField(blank=True, help_text='Electrical Conductivity in µS/cm (Pre Monsson)', null=True)),
                ('post_ec', models.FloatField(blank=True, help_text='Electrical Conductivity in µS/cm (Post Monsson)', null=True)),
                ('pre_tds', models.FloatField(blank=True, help_text='Total Dissolved Solids in mg/L (Pre Monsson)', null=True)),
                ('post_tds', models.FloatField(blank=True, help_text='Total Dissolved Solids in mg/L (Post Monsson)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality_availability_records', to='locationApi.village')),
            ],
            options={
                'verbose_name': 'Water Quality Availability',
                'verbose_name_plural': 'Water Quality Availabilities',
                'db_table': 'waterquality_availability_table',
            },
        ),
    ]
