# Generated by Django 5.2.9 on 2026-01-10 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationApi', '0009_alter_block_name_alter_district_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type', models.CharField(blank=True, max_length=255, null=True)),
                ('other_recharge_structures', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_capacity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_structures', to='locationApi.village')),
            ],
        ),
    ]
