# Generated by Django 5.2.9 on 2026-01-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeStructureApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargestructure',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rechargestructure',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
