# Generated by Django 5.2.9 on 2026-04-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechargeStructureApi', '0002_rechargestructure_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargestructure',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
