# Generated by Django 5.2.9 on 2026-01-05 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauge_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('telemetric', 'Telemetric')], default='manual', max_length=50)),
                ('rainfall_mm', models.FloatField(help_text='Rainfall in millimeters')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_records', to='locationApi.village')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('village', 'date', 'gauge_type')},
            },
        ),
    ]
