# Generated by Django 5.2.9 on 2026-01-30 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfallApi', '0002_rainfall_geo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rainfall',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.CreateModel(
            name='StationRainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('rainfall_mm', models.FloatField(help_text='Rainfall in millimeters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_data', to='rainfallApi.rainfallstation')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('station', 'date')},
            },
        ),
    ]
