# Generated by Django 5.2.9 on 2026-01-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfallApi', '0003_rainfallstation_alter_rainfall_date_stationrainfall'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfallstation',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
