# Generated by Django 5.2.9 on 2026-01-07 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationApi', '0003_village_latitude_village_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquiferData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_id', models.CharField(help_text='Unique identifier for the monitoring well', max_length=100, unique=True)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the well', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the well', null=True)),
                ('well_depth', models.FloatField(blank=True, help_text='Total depth of well in meters', null=True)),
                ('aquifer', models.CharField(blank=True, help_text='Aquifer type/name', max_length=255, null=True)),
                ('pre_2015', models.FloatField(blank=True, help_text='Pre-monsoon 2015 depth to water level (m)', null=True)),
                ('pst_2015', models.FloatField(blank=True, help_text='Post-monsoon 2015 depth to water level (m)', null=True)),
                ('pre_2016', models.FloatField(blank=True, help_text='Pre-monsoon 2016 depth to water level (m)', null=True)),
                ('pst_2016', models.FloatField(blank=True, help_text='Post-monsoon 2016 depth to water level (m)', null=True)),
                ('pre_2017', models.FloatField(blank=True, help_text='Pre-monsoon 2017 depth to water level (m)', null=True)),
                ('pst_2017', models.FloatField(blank=True, help_text='Post-monsoon 2017 depth to water level (m)', null=True)),
                ('pre_2018', models.FloatField(blank=True, help_text='Pre-monsoon 2018 depth to water level (m)', null=True)),
                ('pst_2018', models.FloatField(blank=True, help_text='Post-monsoon 2018 depth to water level (m)', null=True)),
                ('pre_2019', models.FloatField(blank=True, help_text='Pre-monsoon 2019 depth to water level (m)', null=True)),
                ('pst_2019', models.FloatField(blank=True, help_text='Post-monsoon 2019 depth to water level (m)', null=True)),
                ('pre_2020', models.FloatField(blank=True, help_text='Pre-monsoon 2020 depth to water level (m)', null=True)),
                ('pst_2020', models.FloatField(blank=True, help_text='Post-monsoon 2020 depth to water level (m)', null=True)),
                ('pre_2021', models.FloatField(blank=True, help_text='Pre-monsoon 2021 depth to water level (m)', null=True)),
                ('pst_2021', models.FloatField(blank=True, help_text='Post-monsoon 2021 depth to water level (m)', null=True)),
                ('pre_2022', models.FloatField(blank=True, help_text='Pre-monsoon 2022 depth to water level (m)', null=True)),
                ('pst_2022', models.FloatField(blank=True, help_text='Post-monsoon 2022 depth to water level (m)', null=True)),
                ('pre_2023', models.FloatField(blank=True, help_text='Pre-monsoon 2023 depth to water level (m)', null=True)),
                ('pst_2023', models.FloatField(blank=True, help_text='Post-monsoon 2023 depth to water level (m)', null=True)),
                ('pre_2024', models.FloatField(blank=True, help_text='Pre-monsoon 2024 depth to water level (m)', null=True)),
                ('pst_2024', models.FloatField(blank=True, help_text='Post-monsoon 2024 depth to water level (m)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(help_text='Village where the monitoring well is located', on_delete=django.db.models.deletion.CASCADE, related_name='aquifer_records', to='locationApi.village')),
            ],
            options={
                'verbose_name': 'Aquifer Data Record',
                'verbose_name_plural': 'Aquifer Data Records',
                'ordering': ['well_id'],
            },
        ),
    ]
