# Generated by Django 5.2.9 on 2026-04-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquiferApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquiferdata',
            name='aquifer',
            field=models.CharField(blank=True, db_index=True, help_text='Aquifer type/name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aquiferdata',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, help_text='Latitude of the well', null=True),
        ),
        migrations.AlterField(
            model_name='aquiferdata',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, help_text='Longitude of the well', null=True),
        ),
    ]
