# Generated by Django 5.2.9 on 2026-01-29 16:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('layer_type', models.CharField(choices=[('aquifer', 'Aquifer'), ('canal', 'Canal'), ('groundwater_zone', 'Groundwater Zone'), ('waterbody', 'Waterbody')], max_length=50)),
                ('properties', models.JSONField(default=dict, help_text='Store extra GeoJSON properties')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Spatial Layer',
                'verbose_name_plural': 'Spatial Layers',
            },
        ),
    ]
