# Generated by Django 5.2.9 on 2026-04-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layersApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatiallayer',
            name='layer_type',
            field=models.CharField(choices=[('aquifer', 'Aquifer'), ('canal', 'Canal'), ('groundwater_zone', 'Groundwater Zone'), ('waterbody', 'Waterbody')], db_index=True, max_length=50),
        ),
    ]
