# Generated by Django 5.2.9 on 2026-04-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layersApi', '0002_alter_spatiallayer_layer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatiallayer',
            name='area_sqkm',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
