# Generated by Django 5.2.9 on 2026-04-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layersApi', '0003_spatiallayer_area_sqkm'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatiallayer',
            name='aquifer_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
