# Generated by Django 5.2.9 on 2026-01-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='gram_panchayat',
            new_name='grampanchayat',
        ),
        migrations.AlterField(
            model_name='grampanchayat',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grampanchayats', to='locationApi.block'),
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('name', 'grampanchayat')},
        ),
    ]
