# Generated by Django 5.2.9 on 2026-01-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationApi', '0002_rename_gram_panchayat_village_grampanchayat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
