# Generated by Django 5.2.9 on 2026-01-07 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationApi', '0003_village_latitude_village_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_org', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='boundary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='district',
            name='boundary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='grampanchayat',
            name='boundary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grampanchayat',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='state',
            name='boundary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='village',
            name='boundary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
