# Generated by Django 5.2.9 on 2026-01-08 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationApi', '0004_apikey_block_boundary_block_code_district_boundary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grampanchayat',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gram_panchayats', to='locationApi.block'),
        ),
    ]
