# Generated by Django 5.2.9 on 2026-01-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationApi', '0005_alter_grampanchayat_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_name', models.CharField(max_length=255)),
                ('dist_code', models.CharField(max_length=50)),
                ('block_name', models.CharField(max_length=255)),
                ('block_code', models.CharField(max_length=50)),
                ('gp_name', models.CharField(max_length=255)),
                ('gp_code', models.CharField(max_length=50)),
                ('vlg_name', models.CharField(max_length=255)),
                ('vlg_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
