# Generated by Django 5.2.9 on 2026-01-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationApi', '0006_locationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcode',
            name='block_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='locationcode',
            name='block_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='locationcode',
            name='dist_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='locationcode',
            name='dist_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='locationcode',
            name='gp_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
