# Generated by Django 5.2.9 on 2026-01-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationApi', '0007_alter_locationcode_block_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='district',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='grampanchayat',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='state',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='village',
            name='boundary',
        ),
    ]
