# Generated by Django 5.2.9 on 2026-01-07 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationApi', '0003_village_latitude_village_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainGauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauge_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('telemetric', 'Telemetric')], max_length=50)),
                ('rainfall_mm', models.FloatField()),
                ('date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rain_gauges', to='locationApi.village')),
            ],
        ),
    ]
