# Generated by Django 5.2.9 on 2026-01-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationApi', '0003_village_latitude_village_longitude'),
        ('raingaugeApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raingauge',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='raingauge',
            unique_together={('village', 'date', 'gauge_type')},
        ),
    ]
