# Generated by Django 5.2.9 on 2026-01-08 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationApi', '0005_alter_grampanchayat_block'),
        ('raingaugeApi', '0002_alter_raingauge_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raingauge',
            options={'ordering': ['-date'], 'verbose_name': 'Rain Gauge', 'verbose_name_plural': 'Rain Gauges'},
        ),
        migrations.AlterField(
            model_name='raingauge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='raingauge',
            name='date',
            field=models.DateField(help_text='Date of the rainfall measurement'),
        ),
        migrations.AlterField(
            model_name='raingauge',
            name='gauge_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('telemetric', 'Telemetric')], help_text='Type of rain gauge equipment', max_length=50),
        ),
        migrations.AlterField(
            model_name='raingauge',
            name='latitude',
            field=models.FloatField(help_text='Latitude coordinate of the gauge station'),
        ),
        migrations.AlterField(
            model_name='raingauge',
            name='longitude',
            field=models.FloatField(help_text='Longitude coordinate of the gauge station'),
        ),
        migrations.AlterField(
            model_name='raingauge',
            name='rainfall_mm',
            field=models.FloatField(help_text='Rainfall measurement in millimeters'),
        ),
        migrations.AlterField(
            model_name='raingauge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='raingauge',
            name='village',
            field=models.ForeignKey(help_text='Village where the rain gauge is located', on_delete=django.db.models.deletion.CASCADE, related_name='rain_gauges', to='locationApi.village'),
        ),
        migrations.AddIndex(
            model_name='raingauge',
            index=models.Index(fields=['-date'], name='raingaugeAp_date_b69843_idx'),
        ),
        migrations.AddIndex(
            model_name='raingauge',
            index=models.Index(fields=['village', 'date'], name='raingaugeAp_village_9d05a8_idx'),
        ),
    ]
