# Generated by Django 5.2.9 on 2026-01-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationApi', '0003_village_latitude_village_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the well', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the well', null=True)),
                ('well_id', models.CharField(help_text='Unique identifier for the well', max_length=100, unique=True)),
                ('type_of_well', models.CharField(choices=[('bore_well', 'Bore Well'), ('dug_well', 'Dug Well'), ('hand_pump', 'Hand Pump'), ('tube_well', 'Tube Well'), ('open_well', 'Open Well'), ('other', 'Other')], default='bore_well', max_length=50)),
                ('well_depth', models.FloatField(blank=True, help_text='Depth of well in meters', null=True)),
                ('meta_date', models.DateField(help_text='Date of water quality measurement')),
                ('ph', models.FloatField(blank=True, help_text='pH level', null=True)),
                ('hardness', models.FloatField(blank=True, help_text='Hardness in mg/L', null=True)),
                ('alkalinity', models.FloatField(blank=True, help_text='Alkalinity in mg/L', null=True)),
                ('nitrate', models.FloatField(blank=True, help_text='Nitrate in mg/L', null=True)),
                ('fluoride', models.FloatField(blank=True, help_text='Fluoride in mg/L', null=True)),
                ('ec', models.FloatField(blank=True, help_text='Electrical Conductivity in µS/cm', null=True)),
                ('tds', models.FloatField(blank=True, help_text='Total Dissolved Solids in mg/L', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality_records', to='locationApi.village')),
            ],
            options={
                'verbose_name': 'Water Quality Record',
                'verbose_name_plural': 'Water Quality Records',
                'ordering': ['-meta_date'],
                'unique_together': {('well_id', 'meta_date')},
            },
        ),
    ]
