# Generated by Django 5.2.9 on 2026-01-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_qualityApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='waterquality',
            table='water_qualityApi_waterquality',
        ),
    ]
