# Generated by Django 5.2.9 on 2026-04-26 16:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_qualityApi', '0002_alter_waterquality_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterquality',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, help_text='Latitude of the well', null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, help_text='Longitude of the well', null=True),
        ),
        migrations.AlterField(
            model_name='waterquality',
            name='meta_date',
            field=models.DateField(db_index=True, help_text='Date of water quality measurement'),
        ),
        migrations.CreateModel(
            name='WaterQualityContour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(db_index=True, help_text='ec, tds, ph, nitrate, fluoride, etc.', max_length=50)),
                ('meta_date', models.DateField(db_index=True, help_text='Measurement date/year')),
                ('min_value', models.FloatField(help_text='Lower bound of the contour interval')),
                ('max_value', models.FloatField(help_text='Upper bound of the contour interval')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, help_text='Suggested HEX color for the contour polygon', max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('district_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('block_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('gp_id', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Water Quality Contour',
                'verbose_name_plural': 'Water Quality Contours',
                'db_table': 'water_quality_contours',
                'indexes': [models.Index(fields=['parameter', 'meta_date'], name='water_quali_paramet_646c52_idx')],
            },
        ),
    ]
