# Generated by Django 5.2.9 on 2026-04-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_qualityApi', '0003_alter_waterquality_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterquality',
            name='aquifer_type',
            field=models.CharField(blank=True, help_text='Aquifer type/formation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='waterquality',
            name='bicarbonate',
            field=models.FloatField(blank=True, help_text='Bicarbonate in mg/L', null=True),
        ),
        migrations.AddField(
            model_name='waterquality',
            name='calcium',
            field=models.FloatField(blank=True, help_text='Calcium in mg/L', null=True),
        ),
        migrations.AddField(
            model_name='waterquality',
            name='carbonate',
            field=models.FloatField(blank=True, help_text='Carbonate in mg/L', null=True),
        ),
        migrations.AddField(
            model_name='waterquality',
            name='chloride',
            field=models.FloatField(blank=True, help_text='Chloride in mg/L', null=True),
        ),
        migrations.AddField(
            model_name='waterquality',
            name='magnesium',
            field=models.FloatField(blank=True, help_text='Magnesium in mg/L', null=True),
        ),
        migrations.AddField(
            model_name='waterquality',
            name='potassium',
            field=models.FloatField(blank=True, help_text='Potassium in mg/L', null=True),
        ),
        migrations.AddField(
            model_name='waterquality',
            name='site_name',
            field=models.CharField(blank=True, help_text='Name of the measurement site', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='waterquality',
            name='sodium',
            field=models.FloatField(blank=True, help_text='Sodium in mg/L', null=True),
        ),
        migrations.AddField(
            model_name='waterquality',
            name='source',
            field=models.CharField(blank=True, help_text='Data source', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='waterquality',
            name='sulphate',
            field=models.FloatField(blank=True, help_text='Sulphate in mg/L', null=True),
        ),
    ]
